resources:
  - ../../base

namespace: sre-app

patches:
  - path: deployment-patch.yaml
  - path: infra.auto.gateway.patch.yaml
  - path: infra.auto.route.patch.yaml

images:
  - name: sre-app
    newName: asia-east1-docker.pkg.dev/sre-haw-ops/apps/sre-gitops
    newTag: dd21a392748df0bc0c38d5a0057f611232bb7a99
